### ISSUE TITLE
Created tasks don't show up in my Makerlog account

### ISSUE THREAD

**Issue by rasulkireev** [meSingh/alfred-makerlog#1]
I successfully logged in via makerlog-cli. Downloaded the latest release of alfred workflow. Appended makelog to all the available actions ("makerlog todo", etc.). When I submit a todo via alfredI get a success message, but nothing shows up in the account.

This might be vague, but do you have any idea why that might be happening? 
Thanks in advance.

**Comment by natterstefan** [comment]
Hi @rasulkireev,

I have the same issue. Have you resolved it? Thanks for your help.

**Comment by rasulkireev** [comment]
Nope, unfortunately, I didn't.

**Comment by natterstefan** [comment]
Okay, thanks. Maybe this is something for the #hacktoberfest. :)

**Comment by natterstefan** [comment]
Hi @rasulkireev,

I've created a solution 🥳. You can take a look and download it here: https://github.com/meSingh/alfred-makerlog/pull/3.

@meSingh please, take a look at the PR and let me know what you think. Thanks.

**Comment by meSingh** [comment]
@natterstefan It's merged, thanks!

**Comment by natterstefan** [comment]
Thanks a lot @meSingh!
