### ISSUE TITLE
How to sign in to MakerLog CLI if I don't have a password?

### ISSUE THREAD

**Issue by chrismessina** [meSingh/alfred-makerlog#2]
I signed up for MakerLog w/ Twitter, so don't have a password. Is there another way to get an auth token?

**Comment by meSingh** [comment]
@chrismessina you will have to bug @MihaiVoinea for the new way to authenticate the CLI as this workflow uses Makerlog CLI to make requests. 

In the meantime, you can set you the password at https://getmakerlog.com/settings

**Comment by MihaiVoinea** [comment]
Hey @chrismessina and @meSingh!

I'll look into this. Thanks for letting me know!
